---
name: Java CI with Maven
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - name: Package Helm Chart
        run: |
          helm lint mysql
          helm package mysql
deploy-to-eks:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIATZXCDZEGQINIYHRB
        aws-secret-access-key: 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
        aws-region: ap-south-1
    - name: Update Kubeconfig
      run: >
        aws eks --region ap-south-1 update-kubeconfig --name devops

        kubectl get nodes

        helm install mysql /home/runner/work/Calculator/Calculator/mysql-0.1.0.tgz --/home/runner/.kube/config
