# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)  

    - name: Package Helm Chart
      run: |
        helm lint mysql
        helm package mysql

    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIATZXCDZEGQINIYHRB
        aws-secret-access-key: 6YH9JsAdPHWEXZm5D7qNnBx3aT4My/FEyM+jcyaT
        aws-region: ap-south-1  # Replace with your AWS region

    - name: Update Kubeconfig
      run: |
        aws eks --region ap-south-1 update-kubeconfig --name devops
        kubectl get nodes
        helm install mysql /home/runner/work/Calculator/Calculator/mysql-0.1.0.tgz
